name: build
on: pull_request

jobs:
  foxy_build:
    runs-on:  ubuntu-20.04
    
    container: ros:foxy
    services:
      ros:
        image: ros

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rosdep update
        run: |
          apt-get update
          rosdep update
      - name: Create Workspace
        run: |
          mkdir -p ~/pcl_localization_ros2/src/
          cp -r `pwd` ~/pcl_localization_ros2/src/
      - name: Build
        run: |
          cd ~/pcl_localization_ros2/
          source /opt/ros/foxy/setup.bash
          rosdep install --from-paths src --ignore-src -r -y
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests